name: Arte Arena Space Frontend - Production CI/CD Pipeline

on:
  push:
    branches:
      - homolog  # Only trigger on pushes to homolog branch

jobs:
  build_and_push_homolog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Environment for Homolog
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          image_name=artearenahub/space-frontend  # Base image name

          echo "NEXT_PUBLIC_API=https://api-homolog.spacearena.net" > .env
          echo "image_tag=<span class="math-inline">image\_name\-homolog\:0\.0\.</span>{{ github.run_number }}" >> $GITHUB_ENV  # Tag for homolog
          echo "image_tag_latest=$image_name-homolog:latest" >> $GITHUB_ENV  # Tag latest for homolog
          echo "Environment: Homolog"
          echo "Image Tag: ${{ env.image_tag }}"
          echo "Image Tag Latest: ${{ env.image_tag_latest }}"
          echo "Environment file content:"
          cat .env

      - name: Ensure .env is included
        run: |
          ls -la
          if [ ! -f ".env" ]; then
            echo "Error: .env file was not created"
            exit 1
          fi

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker frontend image (Homolog)
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ env.image_tag }}
            ${{ env.image_tag_latest }}
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true

  # Separate job for Pull Requests merged to main
  deploy_to_production:
    runs-on: ubuntu-latest
    needs: build_and_push_homolog  # This job depends on the successful completion of build_and_push_homolog
    if: github.event.name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Environment for Production
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          image_name=artearenahub/space-frontend  # Base image name

          echo "NEXT_PUBLIC_API=https://api.spacearena.net" > .env
          echo "image_tag=<span class="math-inline">image\_name\:0\.0\.</span>{{ github.run_number }}" >> $GITHUB_ENV  # Tag for production
          echo "image_tag_latest=$image_name:latest" >> $GITHUB_ENV  # Tag latest for production
          echo "Environment: Production"
          echo "Image Tag: ${{ env.image_tag }}"
          echo "Image Tag Latest: ${{ env.image_tag_latest }}"
          echo "Environment file content:"
          cat .env

      - name: Ensure .env is included
        run: |
          ls -la
          if [ ! -f ".env" ]; then
            echo "Error: .env file was not created"
            exit 1
          fi

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker frontend image (Production)
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ env.image_tag }}
            ${{ env.image_tag_latest }}
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true