name: Arte Arena Space Frontend - Production CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up .env file
        run: |
          if [[ "${GITHUB_REF#refs/heads/} " == "homolog" ]]; then
            echo "NEXT_PUBLIC_API=https://api-homolog.spacearena.net" > .env
          else
            echo "NEXT_PUBLIC_API=https://api.spacearena.net" > .env
          fi

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker frontend image
        uses: docker/build-push-action@v5.0.0
        with: 
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            if [[ "${GITHUB_REF#refs/heads/} " == "homolog" ]]; then
              artearenahub/space-frontend-homolog:0.0.${{github.run_number}}
              artearenahub/space-frontend-homolog:latest
            else
              artearenahub/space-frontend:0.0.${{github.run_number}}
              artearenahub/space-frontend:latest
            fi
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
