name: Arte Arena Space Frontend - Production CI/CD Pipeline

on:
  push:
    branches: [main, homolog]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set environment based on branch
        run: |
          if [[ "${GITHUB_REF#refs/heads/} " == "homolog" ]]; then
            echo "IMAGE_NAME=artearenahub/space-frontend-homolog"
            echo "IMAGE_TAG=latest"
          else
            echo "IMAGE_NAME=artearenahub/space-frontend"
            echo "IMAGE_TAG=0.0.${{github.run_number}}"
          fi
          echo "## Set additional tags if needed"  # Add more tags here (optional)
          echo "ADDITIONAL_TAGS="  # Define a variable for additional tags (optional)
          

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker frontend image
        run: |
          docker buildx build --file ./docker/Dockerfile \
            --tag "${IMAGE_NAME}:${IMAGE_TAG}" \
            $ADDITIONAL_TAGS  # Add additional tags using the variable (optional)
            --push .
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
