name: Arte Arena Space Frontend - Production CI/CD Pipeline

on:
  push:
    branches: 
      - "main"
      - "homolog"

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Environment
        run: |
          if [[ "${{ github.ref_name }}" == "homolog" ]]; then
            echo "NEXT_PUBLIC_API=https://api-homolog.spacearena.net" > .env
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "NEXT_PUBLIC_API=https://api.spacearena.net" > .env
          fi

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker frontend image
        uses: docker/build-push-action@v5.0.0
        with: 
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: | 
            artearenahub/space-frontend:0.0.${{github.run_number}}
            artearenahub/space-frontend:latest
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
